version: '3'
services:

  backend:
    build: ./backend
    container_name: backend
    ports:
      - 3000:3000

  front-end:
    build: ./front-end
    container_name: front-end
    ports:
      - 8080:8080
    links:
      - backend
